### ISSUE TITLE
Improve UI (in)security indicators on whitelisted sites

### ISSUE THREAD

**Issue by ghost** [nym-zone/block_cloudflare_mitm_fx#11]
1. whitelisted items may fade from the user's memory over time and albeit having deliberately whitelisted an item it might be useful to be reminded/aware nonetheless that one is on a proxy domain (e.g. https://discussions.apple.com), which leads to

1.  `just change titel and favicon` I found not really getting my attention/focus. Isn't there a better/obvious way, e.g. a (semi-transparent) page border (similar like this https://addons.mozilla.org/en-US/firefox/addon/frameyourhosts/ or this https://addons.mozilla.org/en-US/firefox/addon/http-border/)?

**Comment by whatsusername** [comment]
> I found not really getting my attention/focus

Sorry to hear that. I always glance at the URL bar to check the address.
How about changing background color?

**Comment by ghost** [comment]
thanks for the response, presumably user perception/focus is different. I do eventually glance at the url bar too but not necessarly expand to the tab, particulalry with numerous tabs open and the tabs are getting smaller in size, or a pinned tab (really small in size).

Changing the bg colour may interfere with text contrast/readibility and could potentially cause trouble for users with colour blindness.

**Comment by nym-zone** [comment]
Firefox already has some established UI patterns for indicating insecurity, such as a crossed-out lock icon, and (IIRC) potentially changing the background colour of the address bar (not the page).  Time permitting, I may try to come up with some screenshots.

I think it’s important to maintain consistency with existing UI, so as to gain wider acceptance of this functionality.

The crossed-out lock icon would be a good start.  If there is a man-in-the-middle decrypting everything, then that’s simply being honest!  *Maybe* the background colour of the address bar should be changed, but only subtly—not in a way which screams for attention, or impairs readability.

When a user has intentionally whitelisted a site, I don’t think that anything too intrusive should be done to—what?  Nag and annoy the user?  No.  “Mechanism, not policy”—the goal is to provide users with an informed choice, which they don’t have when Cloudflare silently MITMs their connection.  Users are also free to do other dumb things, such as give their passwords out to strangers in exchange for a candy bar.  They are also free to uninstall the add-on, if it annoys them instead of helping them.

**Comment by ghost** [comment]
Thanks for the feedback. With the (semi-tranparent) page border I tought it would be rather subtle, unobstrusive and not nagging but instantly obvious.

**Comment by whatsusername** [comment]
@n8v8R v1.0.9(and above) fixed this by adding visible border (if you select option 2: just change title...).
If not, how can I improve this?

**Comment by ghost** [comment]
border is visible (1 -2 seconds after page load) on new sites when having opted for `Just change title, favicon, and website border`

border unfortunately not visible for whitelisted items regardless of chosen option `Just change title, favicon, and website border` or `Show security warning page`

**Comment by whatsusername** [comment]
@n8v8R

> border is visible (1 -2 seconds after page load) on new sites when having opted for Just change title, favicon, and website border

Yes, it's expected behavior.

> border unfortunately not visible for whitelisted items regardless of chosen option Just change title, favicon, and website border or Show security warning page

Yes, it's also expected because you've "whitelisted"(completely allowed) them.


Should I remove "Just change title, favicon, and website border" option, and apply this to all whitelisted sites?

**Comment by ghost** [comment]
It is working fine in 1.0.9.3. 

I prefer such option to remain in place, one user may like it the next one not.
Perhaps to tone it down to border only, changing the title and favicon is not really necessary with the border now in place and the item being whitelisted.

**Comment by ghost** [comment]
Just stumbled across something strange on 1.0.9.3 / 1.0.9.4

Just one domain whitelisted, in this case oneprovider.com

Set to `Show security warning page`

When browsing another MitM domain e.g. https://whatismyipaddress.com there is no warning page but the border and changes in title and favicon.

Removing the single item from the whitelist and going again to https://whatismyipaddress.com/ the warning page is showing. Adding the exception and then going to https://oneprovider.com/ gets back to the border and changes in title and favicon but no security warning page, as it should happen

**Comment by ghost** [comment]
It seems that the border is applied to the `body` html element. Would it not be better placed with `:root`, which remains static independent of the body element and the monitor size/resolution?
